# Generated by Django 3.2.13 on 2022-06-23 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20220623_1234'),
    ]

    operations = [
        migrations.AddField(
            model_name='symbol',
            name='max_leverage',
            field=models.IntegerField(default=1),
        ),
    ]
