# Generated by Django 3.2.13 on 2022-06-23 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_symbol_max_leverage'),
    ]

    operations = [
        migrations.AddField(
            model_name='candle',
            name='tf',
            field=models.CharField(choices=[('1m', '1m'), ('3m', '3m'), ('5m', '5m'), ('15m', '15m'), ('30m', '30m'), ('1h', '1h'), ('2h', '2h'), ('4h', '4h'), ('6h', '6h'), ('8h', '8h'), ('12h', '12h'), ('1d', '1d'), ('3d', '3d'), ('1w', '1w'), ('1M', '1M')], default='1m', max_length=3),
        ),
    ]
