# Generated by Django 3.2.13 on 2022-06-23 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_candle_tf'),
    ]

    operations = [
        migrations.AddField(
            model_name='symbol',
            name='last_update',
            field=models.DateTimeField(null=True),
        ),
    ]
