# Generated by Django 3.2.13 on 2022-06-23 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_symbol_last_update'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='candle',
            options={'ordering': ('symbol', 'tf', 'open_time')},
        ),
        migrations.CreateModel(
            name='SymbolInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pnl_10', models.FloatField(default=0)),
                ('pnl_25', models.FloatField(default=0)),
                ('pnl_50', models.FloatField(default=0)),
                ('symbol', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.symbol')),
            ],
        ),
    ]
