# Generated by Django 3.2.13 on 2022-07-08 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20220623_1804'),
    ]

    operations = [
        migrations.RenameField(
            model_name='symbolinfo',
            old_name='pnl_10',
            new_name='pnl_1_max',
        ),
        migrations.RemoveField(
            model_name='symbolinfo',
            name='pnl_25',
        ),
        migrations.RemoveField(
            model_name='symbolinfo',
            name='pnl_50',
        ),
    ]
