# Generated by Django 3.2.13 on 2022-07-18 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20220708_0731'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coin',
            options={'ordering': ['coin']},
        ),
        migrations.AlterModelOptions(
            name='symbolinfo',
            options={'ordering': ('-pnl_1_max',)},
        ),
        migrations.AddField(
            model_name='symbolinfo',
            name='pnl_20',
            field=models.FloatField(default=0),
        ),
    ]
