# Generated by Django 3.2.13 on 2022-07-18 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20220718_1040'),
    ]

    operations = [
        migrations.AddField(
            model_name='symbolinfo',
            name='body_mean',
            field=models.FloatField(default=0),
        ),
    ]
